### PR TITLE
inmemory test

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
`curl http://localhost:8000/media/test.bin > /dev/null` On my machine about 280M/s locally.

@gsiv I noticed (add flag `-D headers`) that no content-length header is set in the response, which can easily be added. Can this be a performance improvement, so e.g. the client can reserve memory or so?

### CODE REVIEW

**Comment by jsangmeister** [comment]
@gsiv what about this PR? Do you still need it/are there still possible improvements to do?

**Comment by gsiv** [comment]
> @gsiv what about this PR? Do you still need it/are there still possible improvements to do?

IIRC, we used this patch to analyze a specific performance problem a while back.  I don't think we need it to be merged.

> @gsiv I noticed (add flag `-D headers`) that no content-length header is set in the response, which can easily be added. Can this be a performance improvement, so e.g. the client can reserve memory or so?

I cannot answer this question.  We need someone who understands browsers and the client better than me.  Should it be spun off into a new issue maybe?

**Comment by jsangmeister** [comment]
> I cannot answer this question. We need someone who understands browsers and the client better than me. Should it be spun off into a new issue maybe?

The question is, do we have this someone? :D I would suppose to either close this (if we do not want to further investigate it, from my naive perspective 280M/s sounds pretty high) or create an additional issue for it and leave it open for someone to look for improvements.

**Comment by FinnStutzenstein** [comment]
You can open a new PR if this is needed in the future.

**Pull request closed without merging**
